version: '3.5'

services:
  backend:
    image: hello-backend
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db_psql
      - POSTGRES_PASSWORD=psqlexample
    container_name: backend

  frontend:
    image: hello-frontend
    ports:
      - 5000:5000
    container_name: frontend

  redis:
    image: redis
    ports:
      - 6379:6379
    container_name: redis

  db:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environmnent:
       # password is required, other variables are optional
       POSTGRES_PASSWORD: psqlexample
    container_name: db_psql
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database:
